version: "3.8"
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
  redis:
    image: "redis"
    container_name: redis-session-store
    ports:
      - "6379:6379"
  backend:
    build: ./
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
      - ./env/cloudinary.env
    depends_on:
      - mongodb

volumes:
  data:
